# Generated by Django 5.2.4 on 2025-08-20 17:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('resumes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('score', models.FloatField(blank=True, null=True)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='resumes.resume')),
            ],
        ),
    ]
