# Generated by Django 5.2.4 on 2025-08-21 17:23

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='resume',
            options={'ordering': ['-uploaded_at']},
        ),
        migrations.AlterUniqueTogether(
            name='resume',
            unique_together={('owner',)},
        ),
    ]
