# Generated by Django 5.2.4 on 2025-08-21 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0002_alter_resume_options_alter_resume_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='resume',
            unique_together=set(),
        ),
    ]
