# Generated by Django 5.2.4 on 2025-08-21 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0004_resume_education_resume_projects'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='projects',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
